# Generated by Django 4.0.1 on 2022-02-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aspect2cvssyear_aspect2table_aspect2year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebClickNums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clickNums', models.IntegerField()),
            ],
        ),
    ]
