# Generated by Django 4.0.1 on 2022-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_webclicknums'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordThesaurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesaurus', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=50, null=True)),
                ('component', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
