# Generated by Django 4.0.1 on 2022-02-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_wordtype2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordType',
        ),
    ]
