# Generated by Django 3.2.13 on 2022-06-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_phrase2cve_word2cve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect2TableNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_id', models.CharField(max_length=50)),
                ('aspect_ori', models.CharField(max_length=200, null=True)),
                ('aspect', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
