# Generated by Django 3.2.13 on 2022-06-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aspect2tablenew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspect2cvssyear',
            name='id',
        ),
        migrations.RemoveField(
            model_name='aspect2table',
            name='id',
        ),
        migrations.RemoveField(
            model_name='aspect2year',
            name='id',
        ),
        migrations.AlterField(
            model_name='aspect2cvssyear',
            name='aspect_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aspect2table',
            name='aspect_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aspect2year',
            name='aspect_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
