# Generated by Django 3.2.13 on 2022-06-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220609_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspect2table',
            name='aspect',
            field=models.CharField(default='null', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aspect2table',
            name='aspect_id',
            field=models.CharField(max_length=50),
        ),
    ]
