# Generated by Django 4.0.1 on 2022-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_aspectcompare_databaseindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CveInfoPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cveid', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('component', models.CharField(max_length=50, null=True)),
                ('root', models.CharField(max_length=200, null=True)),
                ('vector', models.CharField(max_length=100, null=True)),
                ('impact', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('remedy', models.CharField(max_length=500, null=True)),
                ('cwe', models.CharField(max_length=100, null=True)),
                ('capec', models.CharField(max_length=100, null=True)),
                ('cvss_score', models.CharField(max_length=20, null=True)),
                ('severity', models.CharField(max_length=20, null=True)),
                ('access', models.CharField(max_length=20, null=True)),
                ('interaction', models.CharField(max_length=50, null=True)),
                ('auth', models.CharField(max_length=20, null=True)),
                ('attack_complex', models.CharField(max_length=20, null=True)),
                ('impact_confidence', models.CharField(max_length=20, null=True)),
                ('impact_integer', models.CharField(max_length=20, null=True)),
                ('impact_available', models.CharField(max_length=20, null=True)),
                ('publish_date', models.CharField(max_length=20, null=True)),
                ('exploit_signature', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
