# Generated by Django 3.2.13 on 2022-06-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_aspectmultiinfonew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspectcompare',
            name='id',
        ),
        migrations.AlterField(
            model_name='aspectcompare',
            name='cveid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
