# Generated by Django 3.2.13 on 2022-06-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20220608_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspectcvssinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cveinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='databaseindicator',
            name='id',
        ),
        migrations.AlterField(
            model_name='aspectcvssinfo',
            name='aspect_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cveinfo',
            name='cveid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='databaseindicator',
            name='cveid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
